// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:d93c1e42-2856-4460-bb07-37c06d3f3c90",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ajzsGMM8X",
    "aws_user_pools_web_client_id": "46750s5iof0tec1jqt6d2pdmof",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://rvzu45sxx5dwhh76nutvectbaa.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
